title: Joy Cordiner
logo: "../joy.png?raw=true"
description:
  First Description if you want it
  <br><br>
  Second Description if you need it
  <br><br>
  <a href="https://www.linkedin.com/joycordiner/">My In Profile</a>
theme: jekyll-theme-minimal
