title: Joy Cordiner
logo: "../joy.png?raw=true"
description:
    5/1 85 Dunlop Street, Glasgow, G1 4ET
    <br><br>
    07839762120
    <br><br>
    joycordiner@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/joycordiner/">My LinkedIn Profile</a>
  <br><br>
  Proficiencies//
    Adobe Photoshop
    <br><br>
    Adobe Illustrator
    <br><br>
    Adobe InDesign
    <br><br>
    Adobe XD
    <br><br>
    Adobe Muse
    <br><br>
    Adobe AfterEffects
    <br><br>
    Microsoft Office Suite
    <br><br>
    InVision
    <br><br>
    LaTeX
    <br><br>
    HTML
    <br><br>
    CSS
    <br><br>
    Markdown
    <br><br>
    Javascript 
    <br><br>
    GitHub
    <br><br>
    JQuery
    <br><br>
    Bootstrap
    <br><br>
    Agile
    <br><br>
  
theme: jekyll-theme-minimal
