title: Joy Cordiner
logo: "../joy.png?raw=true"
description:
    5/1 85 Dunlop Street, Glasgow, G1 4ET
    <br>
    07839762120
    <br>
    joycordiner@gmail.com
    <br><br>
      Proficiencies: "Adobe Photoshop, Adobe Illustrator, Adobe InDesign, Adobe Muse, Adobe AfterEffects, Microsoft Office Suite, InVision, LaTeX, HTML, CSS, Markdown, Javascript, GitHub, JQuery, Bootstrap, Agile."
    <br><br>
    
  <a href="https://www.linkedin.com/joycordiner/">My LinkedIn Profile</a>
theme: jekyll-theme-minimal
