title: Joy Cordiner
logo: "../joy.png?raw=true"
description:
    5/1 85 Dunlop Street, Glasgow, G1 4ET
    07839762120
    joycordiner@gmail.com
  <br><br>
  Second Description if you need it
  <br><br>
  <a href="https://www.linkedin.com/joycordiner/">My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
